import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = process.cwd();
const check = process.argv.includes('--check');
const outputPath = join(root, 'docs/generated/project-reference.md');

const sourceDirs = ['electron', 'sidecar/src', 'src'];
const sourceExtensions = new Set(['.cjs', '.js', '.mjs', '.ts', '.tsx']);

function readJson(path) {
  return JSON.parse(readFileSync(join(root, path), 'utf8'));
}

function extensionOf(path) {
  const index = path.lastIndexOf('.');
  return index === -1 ? '' : path.slice(index);
}

function walk(dir) {
  const absolute = join(root, dir);
  return readdirSync(absolute).flatMap((entry) => {
    const path = join(absolute, entry);
    const stats = statSync(path);
    if (stats.isDirectory()) return walk(relative(root, path));
    return sourceExtensions.has(extensionOf(path)) ? [relative(root, path)] : [];
  });
}

function collectEnvVars() {
  const names = new Set();
  const dotAccess = /process\.env\.([A-Za-z_][A-Za-z0-9_]*)/g;
  const bracketAccess = /process\.env\[['"]([A-Za-z_][A-Za-z0-9_]*)['"]\]/g;

  for (const file of sourceDirs.flatMap(walk).filter((path) => !path.includes('.test.'))) {
    const text = readFileSync(join(root, file), 'utf8');
    for (const match of text.matchAll(dotAccess)) names.add(match[1]);
    for (const match of text.matchAll(bracketAccess)) names.add(match[1]);
  }

  return [...names].sort();
}

function commandTable(title, scripts, prefix = 'npm run') {
  const rows = Object.keys(scripts)
    .sort()
    .map((name) => `| \`${prefix} ${name}\` | \`${scripts[name].replaceAll('|', '\\|')}\` |`);

  return [`## ${title}`, '', '| Command | Script |', '| --- | --- |', ...rows].join('\n');
}

const rootPackage = readJson('package.json');
const sidecarPackage = readJson('sidecar/package.json');
const envVars = collectEnvVars();

const content = `${[
  '# Generated Project Reference',
  '',
  'This file is generated by `npm run docs:generate`. Do not edit it by hand.',
  '',
  commandTable('Root npm scripts', rootPackage.scripts),
  '',
  commandTable('Sidecar npm scripts', sidecarPackage.scripts, 'npm --prefix sidecar run'),
  '',
  '## Environment variables discovered in non-test source',
  '',
  '| Variable | Source |',
  '| --- | --- |',
  ...envVars.map((name) => `| \`${name}\` | See \`.env.example\` for local override guidance. |`),
  '',
].join('\n')}`;

if (check) {
  const current = readFileSync(outputPath, 'utf8');
  if (current !== content) {
    console.error('docs/generated/project-reference.md is stale. Run npm run docs:generate.');
    process.exit(1);
  }
  console.log('Generated documentation is current.');
} else {
  mkdirSync(join(root, 'docs/generated'), { recursive: true });
  writeFileSync(outputPath, content);
  console.log(`Wrote ${relative(root, outputPath)}`);
}
